# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    container_name: wallapop
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
    ports:
      - 27018:27017
